/*
    Problem 2 Description
    
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not
    exceed four million, find the sum of the even-valued terms.
*/

#include <iostream> // printf

int main()
{
    // Inputs
    int maximum = 4000000; // 4 million
    int previous = 1;
    int current = 2;

    int output = 0;

    while (current < maximum)
    {
        if (current % 2 == 0)
        {
            output += current;
        }
        current = current + previous;
        previous = current - previous;
    }
    
    std::printf("%d", output); // 4613732
}